//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViolinSuzuki_Leila.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-VC6AJLL\\SQLEXPRESS;Initial Catalog=VIOLIN_SUZUKI_LEILA;Integr" +
            "ated Security=True")]
        public string VIOLIN_SUZUKI_LEILAConnectionString {
            get {
                return ((string)(this["VIOLIN_SUZUKI_LEILAConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-EEU1F57\\SQLEXPRESS;Initial Catalog=VIOLIN_SUZUKI_LEILA;Integr" +
            "ated Security=True;TrustServerCertificate=True")]
        public string VIOLIN_SUZUKI_LEILAConnectionString1 {
            get {
                return ((string)(this["VIOLIN_SUZUKI_LEILAConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=JUANSANTACROCE\\SQLEXPRESS;Initial Catalog=VIOLIN_SUZUKI_LEILA;Integra" +
            "ted Security=True")]
        public string VIOLIN_SUZUKI_LEILAConnectionString2 {
            get {
                return ((string)(this["VIOLIN_SUZUKI_LEILAConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=NTB62275\\SQLEXPRESS;Initial Catalog=VIOLIN_SUZUKI_LEILA;Integrated Se" +
            "curity=True")]
        public string VIOLIN_SUZUKI_LEILAConnectionString3 {
            get {
                return ((string)(this["VIOLIN_SUZUKI_LEILAConnectionString3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-4LFSFKR\\SQLEXPRESS;Initial Catalog=VIOLIN_SUZUKI_LEILA;Integr" +
            "ated Security=True")]
        public string VIOLIN_SUZUKI_LEILAConnectionString4 {
            get {
                return ((string)(this["VIOLIN_SUZUKI_LEILAConnectionString4"]));
            }
        }
    }
}
